### ISSUE TITLE
plugin doesn't work

### ISSUE THREAD

**Issue by narcis-radu** [szymonkaliski/Pico-Tags-Plugin#1]
I copied the plugin to the plugins folder. When I access Pico I get the following errors:

Notice: Undefined variable: url in ***_\htdocs\pico\plugins\pico_tags.php on line 69
Notice: Undefined variable: file_meta in ***_\htdocs\pico\plugins\pico_tags.php on line 101
Notice: Undefined variable: file_meta in ***_\htdocs\pico\plugins\pico_tags.php on line 101
Notice: Undefined property: Pico_Tags::$current_tag in ***_\htdocs\pico\plugins\pico_tags.php on line 102

**Comment by szymonkaliski** [comment]
Could you check this commit and let me know if this fixed things for you?

https://github.com/szymonkaliski/Pico-Tags-Plugin/commit/32ce82be8e20a0e34e07a51e76c6f41fed45bab0

**Comment by narcis-radu** [comment]
The errors don't appear, but neither the tags .. i double checked the .md content and the template. Do you happen to use a custom version of Pico? I'm using the one downloaded from the website.

**Comment by szymonkaliski** [comment]
Try creating page with "Tags: test" in header, and then go to yoursite.com/tag/test and let me know if you can see anything.

How does you theme `index.html` look like? It needs some changes to display tag names, this is easiest way to display page tags: `{{ meta.tags|join(',') }}`

**Comment by narcis-radu** [comment]
When I go to site/tag/test, the tagged post appears, but I also get an error Undefined variable: file_meta in *****\htdocs\pico\plugins\pico_tags.php on line 101

When I'm browsing the first page, no tags appear. I have the default theme and added the code to display tags:

```
        <div class="tags">
            <!-- display page tags with proper urls -->
            {% for tag in page.tags %}
                    <a href="{{ base_url }}tag/{{ tag }}">#{{ tag }}</a>
            {% endfor %}
        </div>
```

**Comment by szymonkaliski** [comment]
Regarding first error, check this newest commit: https://github.com/szymonkaliski/Pico-Tags-Plugin/commit/ba3d8c990ebaf1e92588324eb5d40f81afd84356?

The code you've posted looks ok, could you send whole index.html of your theme?

If you can see page "site/tag/test" then the plugin works, we just have small problem accessing tag names connected to pages from your theme :)

**Comment by narcis-radu** [comment]
https://github.com/szymonkaliski/Pico-Tags-Plugin/commit/ba3d8c990ebaf1e92588324eb5d40f81afd84356 resolved the error. 

oh, I figured it out ... in the **Usage** section you wrote something like: `{% for tag in page.tags %}`, but it should be `{% for tag in meta.tags %}`

Thanks for the help

**Comment by szymonkaliski** [comment]
Oh, sorry for the problems, I'll fix it right away, thanks! Glad it's working for you now :)

Edit:

Actually it, depends on what you're trying to accomplish, `meta.tags` are for single page, and `page.tags` work if you use them in `{% for page in pages %}` when it's front page (index, or /tag/ page): https://github.com/szymonkaliski/Pico-Tags-Plugin/blob/master/README.md
