### ISSUE TITLE
Combining with Pagination Plugin

### ISSUE THREAD

**Issue by c0nfus3d** [szymonkaliski/Pico-Tags-Plugin#12]
I ran in to problems using your plugin, along with the Pagination plugin.
This is not necessarily an issue, but I am pointing out my solution. 

http://www.joshrichard.net/blog/issues/pico-cms-plugin-integration-issues

**Comment by szymonkaliski** [comment]
Thanks! As stated in readme, this project is depraceted and I'm no longer supporting it. I'm glad you've found a solution that works for you!
