### ISSUE TITLE
Notice: Undefined property: Pico_Tags::$current_tag in

### ISSUE THREAD

**Issue by allanhortle** [szymonkaliski/Pico-Tags-Plugin#2]
My index page traces out this error. 
Also each /tag/tagname page doesn't filter on anything.

**Comment by szymonkaliski** [comment]
Hi, I think there was small stupid mistake in previous revision, try current one → https://github.com/szymonkaliski/Pico-Tags-Plugin/commit/519963e9e071c48ef82f6c275241ed690b6bd310

Let me know if this fixes it for you or if you have any more problems!

**Comment by allanhortle** [comment]
That fixes the errors. But it's still not doing any sort of filtering by tag. It doesn't matter what I type post `tag/` it just displays a list of all the markdown files that have a `tag:` meta

**Comment by allanhortle** [comment]
sorry. Accidentally clicked close.

**Comment by szymonkaliski** [comment]
Could you provide more details? For start please send your theme index.html, and example of post meta.

**Comment by allanhortle** [comment]
That's bizarre. I fixed my problem in this pull request https://github.com/szymonkaliski/Pico-Tags-Plugin/pull/3 but if like you say that breaks your index file, it's probably not fixed. Here is those details, feel free to close this issue. 

index.html:

```
{% if is_front_page %}
    {% for page in pages %}
        <article>
            <h1><a href="{{ page.url }}">{{ page.title }}</a></h1>
            <span class="blog-date">{{page.date}}</span>
            <span class="tags">
                {% for tag in page.tags %}
                    <a href="{{ base_url }}tag/{{ tag }}">#{{ tag }}</a>
                {% endfor %}
            </span>
            <p class="blog-excerpt">{{ page.excerpt }}</p>
        </article>
    {% endfor %}
{% else %}
    <article>
        <h1>{{ meta.title }}</h1>
        <div class="blog-meta">
            <span class="blog-date">{{meta.date}}</span>
            <span class="tags">
                {% for tag in meta.tags %}
                    <a href="{{ base_url }}tag/{{ tag }}">#{{ tag }}</a>
                {% endfor %}
            </span>
        </div>
        <p>{{content}}</p>
    </article>
    {% if prev_page.url %}<a href="{{ prev_page.url }}">prev</a>{% endif %}
    {% if next_page.url %}<a href="{{ next_page.url }}">next</a>{% endif %}
{% endif %}
```

post meta:

```
/*
Title: International Small Arms Traffic Blues
Date: 2005-11-05
Tags: The_Mountain_Goats
Author: John Darnielle,
Email: allanhortle@gmail.com
*/
```

**Comment by szymonkaliski** [comment]
Well, I don't see anything wrong with what you've posted, but I'm not sure what happened, good news is it works for you, and for me, so for the time being I'm closing this issue, and not merging in your code.

If anything changes let me know!
